apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- node-port.yaml
- deployment.yaml

images:
- name: docker.io/gfsekamanya/continuous-delivery-example:latest
  newName: docker.io/gfsekamanya/continuous-delivery-example
  newTag: 1.2.0
